import slugify from '../utils/slugify'

export default {
    title: 'Class',
    name: 'class',
    type: 'document',
    __experimental_actions: ['update', 'create', 'delete', 'publish'],
    fields: [
        {
            title: 'Title',
            name: 'title',
            type: 'string',
            validation: Rule => Rule.required()
        },
        {
            title: 'Content Heading',
            name: 'contentHeading',
            type: 'string',
            validation: Rule => Rule.required()
        },
        {
            title: 'Content',
            name: 'content',
            type: 'array', 
            of: [{type: 'block'}],
            validation: Rule => Rule.required()
        },    
        {
            title: 'Class Image',
            name: 'classImage',
            description: 'An image of the class-type in action',
            type: "image",
        },  
        {
            name: 'slug',
            type: 'slug',
            title: 'Slug',
            description: 'This is required for page routing and can be auto-generated by pressing "generate"',
            options: {
                source: 'title',
                maxLength: 96,
                slugify: title => slugify(title)
            },
            validation: Rule => Rule.required()
        },   
        {
            title: 'SEO / Share Settings',
            name: 'seo',
            type: 'seo'
        }
    ],
    preview: {
        select: {
            title: 'title'
        },
        prepare({ title }) {
            return {
                title
            }
        }
    }
}

