import slugify from '../utils/slugify'

export default {
    title: 'Teacher',
    name: 'teacher',
    type: 'document',
    __experimental_actions: ['update', 'create', 'delete', 'publish'],
    fields: [
        {
            title: 'Name',
            name: 'name',
            type: 'string',
            validation: Rule => Rule.required()
        },
        {
            title: 'Position',
            description: 'The teacher\'s position within the company',
            name: 'position',
            type: 'string',
            validation: Rule => Rule.required()
        },
        {
            title: 'Profile Photo',
            name: 'profilePhoto',
            description: 'The teacher\'s profile photo',
            type: "image",
            validation: Rule => Rule.required()
        },  
        {
            name: 'slug',
            type: 'slug',
            title: 'Slug',
            description: 'This is required for page routing and can be auto-generated by pressing "generate"',
            options: {
                source: 'title',
                maxLength: 96,
                slugify: title => slugify(title)
            },
            validation: Rule => Rule.required()
        }, 
        {
            title: 'SEO / Share Settings',
            name: 'seo',
            type: 'seo'
        }
    ],
    preview: {
        select: {
            title: 'name'
        },
        prepare({ title }) {
            return {
                title
            }
        }
    }
}

